Dev to Main
ParinLL/cyberpower-ups-exporter pull request #1
Opened 2024-07-25 16:25 UTC by ParinLL

2024-07-25 16:35 UTC, Jyny commented on main.go
> +	defer log.Sync()
missing err check

2024-07-25 16:41 UTC, Jyny commented on collector/collector.go
> +			ch <- prometheus.MustNewConstMetric(c.batteryStatus, prometheus.GaugeValue, value)
do not use Must* func before check anything

2024-07-25 16:48 UTC, Jyny requested changes
overall LGTM
use lib with more stable way for production ready

2024-07-25 16:48 UTC, Jyny commented on main.go
> +	defer log.Sync()
missing err check

2024-07-25 16:48 UTC, Jyny commented on collector/collector.go
> +			ch <- prometheus.MustNewConstMetric(c.batteryStatus, prometheus.GaugeValue, value)
do not use Must* func before check anything

2024-07-25 16:48 UTC, Jyny commented on main.go
> +	if err := http.ListenAndServe(addr, nil); err != nil {
add graceful shutdown with os signal trap

2024-07-27 12:00 UTC, ParinLL commented
Merge for First Release

2024-07-27 12:00 UTC, merged